# Generated by Django 3.0.7 on 2020-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=115)),
                ('title', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('section', models.CharField(max_length=115)),
                ('dislikes', models.IntegerField()),
                ('short_version', models.CharField(max_length=1155)),
                ('text', models.TextField()),
            ],
        ),
    ]
