# Generated by Django 3.0.7 on 2020-06-28 13:23

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200627_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('can_write', 'read'),)},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=115, validators=[blog.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_version',
            field=models.CharField(max_length=1155, validators=[blog.models.validate_shortversion]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250, validators=[blog.models.validate_title]),
        ),
    ]
