# Generated by Django 3.0.7 on 2020-06-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200628_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('can_write', 'Can write'), ('can_read', 'Can read'))},
        ),
    ]
