# Generated by Django 3.0.7 on 2020-07-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200629_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_by', models.CharField(max_length=115)),
                ('reason', models.CharField(max_length=415)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
