# Generated by Django 3.0.7 on 2020-07-22 15:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_deleteblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteblog',
            name='reason',
            field=models.CharField(max_length=415, validators=[blog.models.validate_reason]),
        ),
    ]
