# Generated by Django 3.0.7 on 2020-07-23 14:18

from django.db import migrations, models
import ideas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_by', models.CharField(max_length=115)),
                ('reason', models.CharField(max_length=1500, validators=[ideas.models.validate])),
                ('idea', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
