# Generated by Django 3.0.7 on 2020-07-15 19:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=115)),
                ('reason', models.CharField(max_length=1500, validators=[accounts.models.validate_reason])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
