# Generated by Django 3.0.7 on 2020-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200716_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanFromPartOfBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=115)),
                ('banned_by', models.CharField(max_length=115)),
                ('part', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
