# Generated by Django 3.0.7 on 2020-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.IntegerField(default=0),
        ),
    ]
