# Generated by Django 3.0.7 on 2020-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
