# Generated by Django 3.0.7 on 2020-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_reportcomment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=115)),
                ('replied_to', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1915)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
