# Generated by Django 3.0.7 on 2020-07-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_replycommentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplyCommentForm',
            new_name='ReplyComment',
        ),
    ]
